export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_DISCOUNT_REQUEST = 'USER_UPDATE_DISCOUNT_REQUEST';
export const USER_UPDATE_DISCOUNT_SUCCESS = 'USER_UPDATE_DISCOUNT_SUCCESS';
export const USER_UPDATE_DISCOUNT_FAIL = 'USER_UPDATE_DISCOUNT_FAIL';
export const USER_UPDATE_DISCOUNT_RESET = 'USER_UPDATE_DISCOUNT_RESET';

export const USER_UPDATE_ACTIVE_REQUEST = 'USER_UPDATE_ACTIVE_REQUEST';
export const USER_UPDATE_ACTIVE_SUCCESS = 'USER_UPDATE_ACTIVE_SUCCESS';
export const USER_UPDATE_ACTIVE_FAIL = 'USER_UPDATE_ACTIVE_FAIL';
export const USER_UPDATE_ACTIVE_RESET = 'USER_UPDATE_ACTIVE_RESET';

export const USER_CHECK_CODE_REQUEST = 'USER_CHECK_CODE_REQUEST';
export const USER_CHECK_CODE_SUCCESS = 'USER_CHECK_CODE_SUCCESS';
export const USER_CHECK_CODE_FAIL = 'USER_CHECK_CODE_FAIL';
export const USER_CHECK_CODE_RESET = 'USER_CHECK_CODE_RESET';

export const USER_CREATE_PLAN = 'USER_CREATE_PLAN';
export const USER_CREATE_PLAN_SUCCESS = 'USER_CREATE_PLAN_SUCCESS';
export const USER_CREATE_PLAN_FAIL = 'USER_CREATE_PLAN_FAIL';
export const USER_CREATE_PLAN_RESET = 'USER_CREATE_PLAN_RESET';

export const USER_PLANS_REQUEST = 'USER_PLANS_REQUEST';
export const USER_PLANS_REQUEST_SUCCESS = 'USER_PLANS_REQUEST_SUCCESS';
export const USER_PLANS_REQUEST_FAIL = 'USER_PLANS_REQUEST_FAIL';
export const USER_PLANS_REQUEST_RESET = 'USER_PLANS_REQUEST_RESET';

export const USER_UPDATE_PLAN_REQUEST = 'USER_UPDATE_PLAN_REQUEST';
export const USER_UPDATE_PLAN_REQUEST_SUCCESS = 'USER_UPDATE_PLAN_REQUEST_SUCCESS';
export const USER_UPDATE_PLAN_REQUEST_FAIL = 'USER_UPDATE_PLAN_REQUEST_FAIL';
export const USER_UPDATE_PLAN_REQUEST_RESET = 'USER_UPDATE_PLAN_REQUEST_RESET';

export const RESTAURANTS_REQUEST = 'RESTAURANTS_REQUEST';
export const RESTAURANTS_REQUEST_SUCCESS = 'RESTAURANTS_REQUEST_SUCCESS';
export const RESTAURANTS_REQUEST_FAIL = 'RESTAURANTS_REQUEST_FAIL';
export const RESTAURANTS_REQUEST_RESET = 'RESTAURANTS_REQUEST_RESET';
